### ISSUE TITLE
Fix for iOS 13 modal presentation style interfering with the `RangeSlider`

### ISSUE THREAD

**Issue by NSExceptional** [indragiek/InAppViewDebugger#11]
I'm too lazy to make a PR for such a simple change, but if you add this to `RangeSlider` it will fix the issue. Basically, modal sheets are presented with a new style now instead of fullscreen, and this new style allows you to drag anywhere on the sheet to dismiss the sheet. Custom controls need to abort this gesture or the control will not always receive touches.

```swift
override func gestureRecognizerShouldBegin(_ gesture: UIGestureRecognizer) -> Bool {
    return false
}
```

To see this bug in action, run the demo app on iOS 13 in the simulator. Try to drag the `UISlider`, then your `RangeSlider`. It is harder to drag the `RangeSlider`. Now, apply the fix and try again.

**Comment by indragiek** [comment]
Thanks!
