### ISSUE TITLE
OMG, my brother!

### ISSUE THREAD

**Issue by ZhipingYang** [indragiek/InAppViewDebugger#3]
I just ready to refactor the [XYDebugView](https://github.com/ZhipingYang/XYDebugView) in swift and integrate with [VerticalTree](https://github.com/ZhipingYang/VerticalTree), and then I see your open source project here. 😭😰😥😔😑😅😂

**Comment by indragiek** [comment]
Very cool projects! Happy to see that other people are thinking about this as well :)
