### ISSUE TITLE
Why I can't find it from CocoaPods ?

### ISSUE THREAD

**Issue by yuehengwu** [indragiek/InAppViewDebugger#5]
Pod search InAppViewDebugger , 
Nothing ...

**Comment by indragiek** [comment]
I'm not sure why it doesn't come up in search, but it is there: https://cocoapods.org/pods/InAppViewDebugger

**Comment by faimin** [comment]
remove pod search index first, 

```shell
rm ~/Library/Caches/CocoaPods/search_index.json
```
then  `pod repo update` , finally search. it work to me.

**Comment by yuehengwu** [comment]
> remove pod search index first,
> 
> ```shell
> rm ~/Library/Caches/CocoaPods/search_index.json
> ```
> 
> then `pod repo update` , finally search. it work to me.

Appreciate , it also works to me !
