### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by DJBen** [indragiek/InAppViewDebugger#8]
It would be nice to have SPM support given that iOS projects can now use SPM for dependency.

**Comment by amelnychuck** [comment]
+1 to this!

**Comment by McProb** [comment]
@indragiek Hello!  I have a patch for this if you could grant me access to push a branch.  Tyler mentioned he had spoken with you earlier.

**Comment by indragiek** [comment]
@McProb Hi! You can fork the repo, create a branch in your fork, push your changes, and then open a pull request on this repo.

**Comment by McProb** [comment]
Thank you for the guidance.  I'll have it up early tomorrow, I expect.  And thanks for the great project.

**Comment by indragiek** [comment]
Contributed by @McProb in #12, this is merged, closing this issue and will publish a new release.
